/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedWasteRouteImport } from './routes/_authed.waste'
import { Route as AuthedReportsRouteImport } from './routes/_authed.reports'
import { Route as AuthedPromotionsRouteImport } from './routes/_authed.promotions'
import { Route as AuthedProfileRouteImport } from './routes/_authed.profile'
import { Route as AuthedPrepRouteImport } from './routes/_authed.prep'
import { Route as AuthedMemoryRouteImport } from './routes/_authed.memory'
import { Route as AuthedInventoryRouteImport } from './routes/_authed.inventory'
import { Route as AuthedForecastRouteImport } from './routes/_authed.forecast'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWasteRoute = AuthedWasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPromotionsRoute = AuthedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPrepRoute = AuthedPrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMemoryRoute = AuthedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryRoute = AuthedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedForecastRoute = AuthedForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/forecast': typeof AuthedForecastRoute
  '/inventory': typeof AuthedInventoryRoute
  '/memory': typeof AuthedMemoryRoute
  '/prep': typeof AuthedPrepRoute
  '/profile': typeof AuthedProfileRoute
  '/promotions': typeof AuthedPromotionsRoute
  '/reports': typeof AuthedReportsRoute
  '/waste': typeof AuthedWasteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/forecast': typeof AuthedForecastRoute
  '/inventory': typeof AuthedInventoryRoute
  '/memory': typeof AuthedMemoryRoute
  '/prep': typeof AuthedPrepRoute
  '/profile': typeof AuthedProfileRoute
  '/promotions': typeof AuthedPromotionsRoute
  '/reports': typeof AuthedReportsRoute
  '/waste': typeof AuthedWasteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/forecast': typeof AuthedForecastRoute
  '/_authed/inventory': typeof AuthedInventoryRoute
  '/_authed/memory': typeof AuthedMemoryRoute
  '/_authed/prep': typeof AuthedPrepRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/promotions': typeof AuthedPromotionsRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/waste': typeof AuthedWasteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/forecast'
    | '/inventory'
    | '/memory'
    | '/prep'
    | '/profile'
    | '/promotions'
    | '/reports'
    | '/waste'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/forecast'
    | '/inventory'
    | '/memory'
    | '/prep'
    | '/profile'
    | '/promotions'
    | '/reports'
    | '/waste'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/dashboard'
    | '/_authed/forecast'
    | '/_authed/inventory'
    | '/_authed/memory'
    | '/_authed/prep'
    | '/_authed/profile'
    | '/_authed/promotions'
    | '/_authed/reports'
    | '/_authed/waste'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/waste': {
      id: '/_authed/waste'
      path: '/waste'
      fullPath: '/waste'
      preLoaderRoute: typeof AuthedWasteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/promotions': {
      id: '/_authed/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthedPromotionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/prep': {
      id: '/_authed/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof AuthedPrepRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/memory': {
      id: '/_authed/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthedMemoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory': {
      id: '/_authed/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthedInventoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/forecast': {
      id: '/_authed/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AuthedForecastRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedForecastRoute: typeof AuthedForecastRoute
  AuthedInventoryRoute: typeof AuthedInventoryRoute
  AuthedMemoryRoute: typeof AuthedMemoryRoute
  AuthedPrepRoute: typeof AuthedPrepRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedPromotionsRoute: typeof AuthedPromotionsRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedWasteRoute: typeof AuthedWasteRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedForecastRoute: AuthedForecastRoute,
  AuthedInventoryRoute: AuthedInventoryRoute,
  AuthedMemoryRoute: AuthedMemoryRoute,
  AuthedPrepRoute: AuthedPrepRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedPromotionsRoute: AuthedPromotionsRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedWasteRoute: AuthedWasteRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
